<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>order_id_2</name>
   <tag></tag>
   <elementGuidId>56a8b9a6-6640-44fc-8530-a5b0f216d210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::td[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tbody > tr > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ff540079-2a2a-4576-9193-2348435f14ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>5559f703-6de6-4d2d-8a53-e9a9c3dfe258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;order&quot;]/div[@class=&quot;content&quot;]/table[@class=&quot;order-table&quot;]/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>0101d088-7210-40bf-aeff-7e9ab694c9c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::td[1]</value>
      <webElementGuid>bdd24b42-ad3b-47eb-aa58-60425ed96055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Price'])[1]/following::td[2]</value>
      <webElementGuid>cf13f78c-84ff-4113-a73a-60b541f172c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thu Mar 21 2024 15:15:11 GMT+0000 (Coordinated Universal Time)'])[1]/preceding::td[1]</value>
      <webElementGuid>2496bcaa-7870-469f-9379-16dbee92d6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='username'])[1]/preceding::td[2]</value>
      <webElementGuid>b0efe8d4-6146-45ff-8db0-67dc351e4183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='45']/parent::*</value>
      <webElementGuid>03a39090-6075-4347-b8ff-cbe3e3e702ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td</value>
      <webElementGuid>82c2b524-c7ab-44bd-b607-b1a72300c513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '45' or . = '45')]</value>
      <webElementGuid>e257053c-e68b-49e0-a6e9-6c498b69379d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
