<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_bar</name>
   <tag></tag>
   <elementGuidId>5870750f-4d77-4c2a-9ce8-f53dcfa4014e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='search'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.top > div.bottom > div.flex-container > form.search > input[name=&quot;search&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9951b1e-50be-4dbb-82d8-219160e23c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-box</value>
      <webElementGuid>ba86b6c7-f210-452e-ae00-e4d6344da022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>0f1aeda3-e11a-4455-bcf7-a120c7553ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search order ID or product ID</value>
      <webElementGuid>8c76371a-928f-4b52-847d-a829481496c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;order&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;sort-menu&quot;]/div[@class=&quot;top&quot;]/div[@class=&quot;bottom&quot;]/div[@class=&quot;flex-container&quot;]/form[@class=&quot;search&quot;]/input[@class=&quot;search-box&quot;]</value>
      <webElementGuid>40d1704d-544d-4fa3-9176-aae4b9d4a010</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='search'])[2]</value>
      <webElementGuid>23a70887-4411-4719-b4a9-2ea6c8846be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/input</value>
      <webElementGuid>7d1f0e5e-5e42-4729-a2bd-ea1037450d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'search' and @placeholder = 'Search order ID or product ID']</value>
      <webElementGuid>0d52f483-2334-4941-ac69-9d27c670931f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
