<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_button</name>
   <tag></tag>
   <elementGuidId>3ad29770-0d8c-42c2-b399-0d118e890477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/form/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.top > div.bottom > div.flex-container > form.search > button.search-button > i.fa-solid.fa-magnifying-glass</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>65ba4ca6-4052-4e40-938a-2e89589845fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-magnifying-glass</value>
      <webElementGuid>c6a583ef-cfe9-4632-a58f-bb389994426c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a5b19763-e101-4dd7-9ea9-d60cc8833db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;order&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;sort-menu&quot;]/div[@class=&quot;top&quot;]/div[@class=&quot;bottom&quot;]/div[@class=&quot;flex-container&quot;]/form[@class=&quot;search&quot;]/button[@class=&quot;search-button&quot;]/i[@class=&quot;fa-solid fa-magnifying-glass&quot;]</value>
      <webElementGuid>ee5168c9-fcf7-4576-b5bb-b4fa157a4c36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/button/i</value>
      <webElementGuid>43687c0a-be5e-423d-9dd2-247d3555e235</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
