<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchbar</name>
   <tag></tag>
   <elementGuidId>d5257f3d-2d9f-449a-a6ba-8833551d3e34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchBar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchBar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0337b37-4719-482b-9903-d70e0c52c339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control me-2</value>
      <webElementGuid>eaa14369-edf4-4820-a86b-4531f8eb390d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>eebb6908-1192-4e45-84e2-c61dd0dff840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>b1e35d6d-078d-4f7c-9792-94e96536529e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>4bded04a-437a-4eae-8dad-a368eb350d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchBar</value>
      <webElementGuid>ec85332c-d892-47f7-99d0-b1300622a3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchBar</value>
      <webElementGuid>45a1d42f-f6e4-419a-8143-0f1972013378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchBar&quot;)</value>
      <webElementGuid>9061765d-2ccf-4c2d-a4e5-56eccf52e020</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchBar']</value>
      <webElementGuid>8ab71733-03c4-49e6-bd0d-a8b574401000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/form/input</value>
      <webElementGuid>c02bd408-0fbb-4c4c-8ec2-0b051a9a02fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1c6c9d5f-232b-4a15-b4ea-5f68d2625959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Search' and @id = 'searchBar' and @name = 'searchBar']</value>
      <webElementGuid>b4009a24-d9cb-466f-9d02-33d4689f23d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
