<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Restock_page-number</name>
   <tag></tag>
   <elementGuidId>d5d2a79d-d0a4-49dd-9a5d-84a3dd42da32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//html/body/div/div[4]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.page-select > input.page-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b7d9961-0248-4b1c-8f83-3c8f05b1a820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-number</value>
      <webElementGuid>35243815-fd3c-412c-b444-871f49d50e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8f7ba1cd-5dac-4e48-87ae-1aeee0f51663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>384f2c7d-0cd8-49e6-bf6c-8a2a3fc50eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f6aa964b-6123-4032-8974-66b61a2ac5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>goToPage(this.value)</value>
      <webElementGuid>23f6997e-b04f-4f70-8001-9fec4cd2dd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;content&quot;]/div[@class=&quot;page-select&quot;]/input[@class=&quot;page-number&quot;]</value>
      <webElementGuid>d1a84f43-bf97-404f-870d-8abafcc98bb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='1'])[3]</value>
      <webElementGuid>248fae38-2e17-4e19-ad05-876a55794659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>af1ea9dc-d32f-44f2-95f7-b7aacb7c7971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>bcb2341b-b52b-408b-a84a-e40e7ce00150</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
