<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>itemPrice</name>
   <tag></tag>
   <elementGuidId>b97da710-fbab-4282-982d-734261c4be18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//html/body/div/div/div[1]/div[2]/table/tbody/tr/td[3]/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.product-price > p:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0855d70f-8606-4799-8eaa-af995c78343c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>฿25.00</value>
      <webElementGuid>e74f819f-4809-43c7-b7b5-6daec2db2e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-fluid row main&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 box-left&quot;]/div[@class=&quot;book-item&quot;]/table[@class=&quot;custom-table&quot;]/tbody[@class=&quot;item-frame&quot;]/tr[1]/td[@class=&quot;product-price&quot;]/p[2]</value>
      <webElementGuid>e84be872-2137-4e1f-aa89-c10c8133a606</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='book 3'])[1]/following::p[4]</value>
      <webElementGuid>1fc7d1d1-0b87-4d6f-ac81-f53ceb77fc9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[1]/following::p[4]</value>
      <webElementGuid>85e33867-0e19-493f-a865-08df129b5ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::p[2]</value>
      <webElementGuid>fe893da0-686a-451f-98e6-14b86db294b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::p[2]</value>
      <webElementGuid>1dd2c2ec-5b3c-4ec8-82d1-7e14333a27ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='฿25.00']/parent::*</value>
      <webElementGuid>f606333c-e8e0-461f-84f1-0c0ec42af161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/p[2]</value>
      <webElementGuid>5032f225-d26e-41ce-9440-c4346998f421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '฿25.00' or . = '฿25.00')]</value>
      <webElementGuid>3a511697-b6f0-472a-90fa-b85f29ca6987</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
