<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_50.00_1_2</name>
   <tag></tag>
   <elementGuidId>2be9b193-8387-4021-b325-f27e87334bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='estTotal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#estTotal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c45cef84-287e-4742-87a4-dee3ccb1cdf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-self-end sum</value>
      <webElementGuid>5b535a59-e1da-42be-b59a-bee3a8c56438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>estTotal</value>
      <webElementGuid>074a9afa-5a99-4e1d-9d21-835495841bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>฿50.00</value>
      <webElementGuid>f7446644-27e1-4d96-8a9e-5c9c1470aa45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;estTotal&quot;)</value>
      <webElementGuid>2f33f243-a850-4ca2-8fb5-9e96ee54e0fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='estTotal']</value>
      <webElementGuid>3a0f038d-2b03-49e1-ae67-030ba8e9c570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::p[8]</value>
      <webElementGuid>827a004c-7ffb-423d-af6d-9969bd4b3e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Promotion code'])[1]/following::p[8]</value>
      <webElementGuid>d1da187d-584f-437a-b1bf-c70c682b6a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/preceding::p[1]</value>
      <webElementGuid>1a247ae7-3719-4f16-b995-d23a0019e637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Heaven'])[1]/preceding::p[1]</value>
      <webElementGuid>01f8ab85-e6d5-4b2a-9fd1-a1afd6262dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p[2]</value>
      <webElementGuid>8bcb6008-69e3-45cb-811a-f87f3d0c0d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'estTotal' and (text() = '฿50.00' or . = '฿50.00')]</value>
      <webElementGuid>6adb8d79-c6b4-4d18-b547-3b96c2453ec0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
