<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_50.00</name>
   <tag></tag>
   <elementGuidId>bfe3917c-db59-4055-b0a0-fbb55d5e44c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.sum</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b32f2ef0-a1d7-446a-80cd-dac0cc6aa55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sum</value>
      <webElementGuid>b70fddf8-96f9-4808-a929-f50ad588d255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>฿50.00</value>
      <webElementGuid>04e1e9c2-279d-4e31-ba47-9de5ad9a513f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-fluid row main&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 box-left&quot;]/div[@class=&quot;book-item&quot;]/table[@class=&quot;custom-table&quot;]/tbody[@class=&quot;item-frame&quot;]/tr[1]/td[5]/p[@class=&quot;sum&quot;]</value>
      <webElementGuid>ec86ef07-a76f-4d65-9d4e-2af19cc3102f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::p[2]</value>
      <webElementGuid>f47dede8-e908-4094-b14d-635fd9cf7a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::p[2]</value>
      <webElementGuid>1ea86e2d-1dad-46fb-a0a5-6e282ba47ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Promotion code'])[1]/preceding::p[1]</value>
      <webElementGuid>a43658a1-829d-4a9a-b277-9f23963edf4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::p[1]</value>
      <webElementGuid>0d5667a3-0860-40a9-bc77-b32ec19071ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='฿50.00']/parent::*</value>
      <webElementGuid>9cff9eb8-79cd-4911-b2e3-cad6c60cf48f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/p[2]</value>
      <webElementGuid>688b9ca4-2faf-4060-a75f-649ff4e61a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '฿50.00' or . = '฿50.00')]</value>
      <webElementGuid>69fbb816-b5d9-4970-9773-d5f51091876f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
