<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_50.00_1</name>
   <tag></tag>
   <elementGuidId>a6bdc67d-d38b-4fc6-a343-3678f10a7487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='subtotal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#subtotal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a9ac8e12-5b4e-472f-b43e-e5b74a7caad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-self-end</value>
      <webElementGuid>836b58c0-2adf-4f64-88af-20a10f5daea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subtotal</value>
      <webElementGuid>9ab4a487-891d-419e-b2a0-0efbca2342f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>฿50.00</value>
      <webElementGuid>71896725-f099-434f-b5de-3e9a68c54e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subtotal&quot;)</value>
      <webElementGuid>8a17cf51-c851-41d9-b7fc-81c8d2bb3b4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='subtotal']</value>
      <webElementGuid>4bf581bc-48be-41f2-bde7-4dc3dc5cb0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::p[2]</value>
      <webElementGuid>69b2e190-df8a-48d5-9904-02b51c77e5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Promotion code'])[1]/following::p[2]</value>
      <webElementGuid>dae85a19-417c-469a-9a32-3ba227229128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/preceding::p[7]</value>
      <webElementGuid>ac5e0317-d1a8-4882-9bfb-fd6018734a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Heaven'])[1]/preceding::p[7]</value>
      <webElementGuid>27b5a35b-db85-43f3-9df1-8c68be7e53ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p[2]</value>
      <webElementGuid>20347a29-b964-4eaa-a009-c11a53094c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'subtotal' and (text() = '฿50.00' or . = '฿50.00')]</value>
      <webElementGuid>047a582e-0f5f-4038-a326-7e522fbb7aa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
