<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxTravel</name>
   <tag></tag>
   <elementGuidId>5750f494-89df-408e-9217-52cb8fb1534c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#categoryCheckbox8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='categoryCheckbox8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75ccd469-4a9e-4c83-8654-a8756d5a6690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input category-checkbox</value>
      <webElementGuid>f5215445-e25c-4091-a98f-464e8bf49c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>951801d0-069e-43f3-b9f6-03982c8fa1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>80f37ad0-226a-4370-8e52-0f6e1e8f108c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categoryCheckbox8</value>
      <webElementGuid>117848c0-435e-4cac-a761-40bb849da010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoryCheckbox8&quot;)</value>
      <webElementGuid>84a9fac3-1d64-48bb-a120-ea42fd331cca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='categoryCheckbox8']</value>
      <webElementGuid>970bee80-7b2d-40fa-b92f-7172f8ab47a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>e8666de0-bcac-458a-95a0-6fea12e58348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'categoryCheckbox8']</value>
      <webElementGuid>6342625f-592d-424b-b10b-2e22573d19f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
