<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxNonFiction</name>
   <tag></tag>
   <elementGuidId>5cba8e87-fca9-4a09-8866-07e80c916025</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#categoryCheckbox2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='categoryCheckbox2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f152424-a312-4fce-ba49-cbef0227bdc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input category-checkbox</value>
      <webElementGuid>eb799b38-409e-4918-b8b1-0b557b49315f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b88cdaaf-97d3-4ac5-821a-11002da49401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ce9d6016-0790-4b18-a7ef-f674c9aa13e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categoryCheckbox2</value>
      <webElementGuid>6f2c6095-4dd2-4f4b-b385-7135bd432c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoryCheckbox2&quot;)</value>
      <webElementGuid>950bf867-1f97-43dd-ae76-7f0f438dc199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='categoryCheckbox2']</value>
      <webElementGuid>30149315-15fb-44d1-aa82-750fbb54fc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>61810f36-cec6-43e6-9a0c-30233a241541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'categoryCheckbox2']</value>
      <webElementGuid>905a6423-4d2f-4587-abb6-d4d943ebf510</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
