<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxFiction</name>
   <tag></tag>
   <elementGuidId>8a96d6ec-c5a9-47e2-bf55-6574e25e8b45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#categoryCheckbox1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='categoryCheckbox1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7891d1dd-4dbb-47f6-afcf-abe2383c0919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input category-checkbox</value>
      <webElementGuid>ff95edc8-7e8b-4596-9fed-fd71416081e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6bab6acb-ae12-4f83-a991-4eee2ac671e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7c0d742a-b00b-4943-b1bc-9dfadf2c1588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categoryCheckbox1</value>
      <webElementGuid>42e62867-bf47-42d8-bb63-ba48f041b7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoryCheckbox1&quot;)</value>
      <webElementGuid>93101107-78f3-4bdb-a8eb-d6f74399164b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='categoryCheckbox1']</value>
      <webElementGuid>5f518f77-5e40-4522-8a68-b15d39e6ea61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>bf9d9576-2da0-47d9-aed0-0190fa513c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'categoryCheckbox1']</value>
      <webElementGuid>13377fcf-bffb-4e04-9078-93610316f113</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
