<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxPerdev</name>
   <tag></tag>
   <elementGuidId>f4ce4cf5-46ae-4264-a106-45182bdc2e8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#categoryCheckbox6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='categoryCheckbox6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50ec935a-bcc7-444e-86b6-209a97a85db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input category-checkbox</value>
      <webElementGuid>3510b6d3-4a63-4130-9f32-8f00d04e4807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>95fc542f-a69e-41f0-b032-346507d160ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>81133593-fd46-4179-bb7c-14eed57fad5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categoryCheckbox6</value>
      <webElementGuid>5b15b64c-ced3-4289-b1c1-8fb5d56b8af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoryCheckbox6&quot;)</value>
      <webElementGuid>24a41231-21aa-47a8-a60c-04247a9b8557</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='categoryCheckbox6']</value>
      <webElementGuid>2cb2d683-93ee-450d-8982-b28b1000fed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>8c14b9b7-cb6e-4743-96a3-9424246dfe67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'categoryCheckbox6']</value>
      <webElementGuid>3cc0f4f8-8880-4462-bdee-461219fe27e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
