<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxNovel</name>
   <tag></tag>
   <elementGuidId>3ee5a4fc-b67d-4d65-9d21-f3b6ffb49e4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#categoryCheckbox4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='categoryCheckbox4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0429f5e-5fa3-4ec0-adbd-30540dd724db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input category-checkbox</value>
      <webElementGuid>23a5e680-d80d-4ec4-bd0f-a9a99d3735d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9fbd68e0-b22c-42bb-885d-e8433ff19851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5e0d8cf0-7dad-46d5-9cb8-380786669405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categoryCheckbox4</value>
      <webElementGuid>d628dd16-0340-4824-8818-5be04f573935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoryCheckbox4&quot;)</value>
      <webElementGuid>abf609b4-e298-421f-9467-8eaf7de36e2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='categoryCheckbox4']</value>
      <webElementGuid>5d9709a0-dbc6-411d-80b7-a45982115503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>7ac84b36-ff8b-4cef-9f0f-7732b8cc6583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'categoryCheckbox4']</value>
      <webElementGuid>e4e3527e-5ed3-4c74-9536-31e5b25ac075</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
