<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test search, category and add item function</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>135e28b2-963f-4219-981f-d7f51dab5c14</testSuiteGuid>
   <testCaseLink>
      <guid>5f5879ba-593a-4cec-ae0a-da802bc539f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FrontEnd/Test search</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>29fb8d64-3b80-4f41-90ce-21bda76ba261</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data file for search test</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>29fb8d64-3b80-4f41-90ce-21bda76ba261</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Search</value>
         <variableId>dc1f897c-eb68-461f-b9e4-0154ed7edd78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>29fb8d64-3b80-4f41-90ce-21bda76ba261</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Bookname</value>
         <variableId>90269dab-4949-4bcd-91bf-94c64bba94ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e66283d-117e-4df3-b333-89e82f0addc5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FrontEnd/Test category</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>442afbb1-4c83-4203-83c9-b846c7754740</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0f75e47-3566-4495-b809-df807d4b746b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9450e926-6f90-4db6-ba84-b949901b46f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6fd9277-28c3-439d-ba15-027fe1e40098</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c31b625-1c8c-4f05-8e21-7ca707ddac08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02d71e98-9977-47f0-b87d-985d7fd4f267</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c8bca35-0628-457c-95f1-b0ac56af3105</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5783febb-4548-4589-a6a7-fcbca381b597</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffbc4358-af45-42d6-9390-97f731e58740</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36667d9a-7077-480b-9e6f-cf8351fb8971</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8c88dd0-52ed-4a5c-a32d-f2a8f98e135d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FrontEnd/Add item to basket from homepage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
