<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>registerBox</name>
   <tag></tag>
   <elementGuidId>0fc99b17-65cc-4f1b-a11f-338b16cdaa00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PASSWORD_confirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PASSWORD_confirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>466953ff-9807-4b4b-8d25-90def4098da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5733f1db-1fc0-4d9d-b39f-1e38161eadec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PASSWORD_confirm</value>
      <webElementGuid>8a766332-55d1-4682-a2f9-0edea2798e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm your password</value>
      <webElementGuid>bce55a68-5cb5-41d6-bfaa-f911977f931c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PASSWORD_confirm</value>
      <webElementGuid>c8720d0a-5317-48dc-8e86-afb8fbabb2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PASSWORD_confirm&quot;)</value>
      <webElementGuid>b22da935-43cb-4a55-8f42-f2b3132aa519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PASSWORD_confirm']</value>
      <webElementGuid>733ffcb2-e832-48d0-bdca-bdcf0cf72a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='register-form']/div/input[4]</value>
      <webElementGuid>9844457e-e49c-4173-a96e-5604983bbbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>f1bbb834-cab4-4e84-9174-1f3056c45acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'PASSWORD_confirm' and @placeholder = 'Confirm your password' and @name = 'PASSWORD_confirm']</value>
      <webElementGuid>fb1022f7-5073-4644-9c03-ceaeb91792df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
