<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tickbox</name>
   <tag></tag>
   <elementGuidId>7f41107c-ffb1-4ee4-90ef-940e70c775ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='selectedCategories']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;selectedCategories&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a5c2d52-6170-4956-8a34-634773031d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ed4ff58c-57bb-4316-8f5d-44906cad0c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedCategories</value>
      <webElementGuid>ebadf223-021d-481f-8375-a474ff622e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>99ee0153-b6a1-4222-bad5-94b9755bd2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableBody&quot;)/tr[1]/td[@class=&quot;checkbox-column&quot;]/input[1]</value>
      <webElementGuid>60eb0a11-0fbe-4526-b293-a660e922ae15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='selectedCategories']</value>
      <webElementGuid>013ba94f-2d81-4cdb-99b2-32956ffc679e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tableBody']/tr/td/input</value>
      <webElementGuid>1661008f-5e04-4ec1-a5be-8b7bff372d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td/input</value>
      <webElementGuid>7a64fae4-ad39-4e86-a501-dcedf7139483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'selectedCategories']</value>
      <webElementGuid>4a3d4f9e-9593-4e1d-825a-f2adad8d2fe1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
