<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to Cart</name>
   <tag></tag>
   <elementGuidId>a67c6782-b40b-40b5-848e-f46c7766cd23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>931ec878-c8af-4ce9-9f45-ec94971e94ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning w-75</value>
      <webElementGuid>18fb874c-ad64-4c83-bbfb-c1b24426adb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0b39f940-5dfa-45c8-b601-c7751e2a75d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Cart</value>
      <webElementGuid>291a0a7e-f045-4132-a39c-089238c2fd26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myCarousel1&quot;)/div[@class=&quot;carousel-inner w-100&quot;]/div[@class=&quot;carousel-item active&quot;]/div[@class=&quot;col-4 col-lg-2&quot;]/a[@class=&quot;text-dark&quot;]/div[@class=&quot;card border-0 position-relative&quot;]/div[@class=&quot;card-body px-0&quot;]/form[1]/button[@class=&quot;btn btn-warning w-75&quot;]</value>
      <webElementGuid>70331f07-e571-4400-910e-13ef2c3e74be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>150a1d78-868a-42f8-8477-3ec45ee77a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myCarousel1']/div/div/div[2]/a/div/div/form/button</value>
      <webElementGuid>b483b0ce-ac4e-4ae6-af98-7452069a7b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Northern Italy: Emilia-Romagna'])[1]/following::button[1]</value>
      <webElementGuid>ccd07d0a-384e-416e-90ee-e0bcdf091022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Cart'])[1]/following::button[1]</value>
      <webElementGuid>c4a87c43-2463-42db-b9bb-36deb053fbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='book 9'])[1]/preceding::button[1]</value>
      <webElementGuid>cb6b0559-af14-4c07-8742-9273f0d47b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Cart'])[3]/preceding::button[1]</value>
      <webElementGuid>0dda5b3f-c126-4656-b0cd-8c6c332b6a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div/form/button</value>
      <webElementGuid>f1877743-960b-46a4-803b-df3ed7e5f6d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Add to Cart' or . = 'Add to Cart')]</value>
      <webElementGuid>c5383cae-ae7e-41ac-861b-4a948547bc61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
