<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EstTotal</name>
   <tag></tag>
   <elementGuidId>3132c0c1-9a83-41f5-819c-e80359d01d28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#estTotal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='estTotal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>930abb94-1290-47c3-986e-a95c2fcdf21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-self-end sum</value>
      <webElementGuid>b32af7a3-02e0-4e01-8c38-44b19594caad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>estTotal</value>
      <webElementGuid>0b079b7a-d75e-42ab-8bf6-038c16fd91e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>฿350.00</value>
      <webElementGuid>ebabb837-c2e2-472d-bfee-862adbea9dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;estTotal&quot;)</value>
      <webElementGuid>f78109a9-7165-48dd-9efe-9633a602b2e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='estTotal']</value>
      <webElementGuid>5d98689b-a250-4246-a6a8-913f109bb876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::p[8]</value>
      <webElementGuid>7f75a6eb-2620-4510-9f72-9816db9b9055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Promotion code'])[1]/following::p[8]</value>
      <webElementGuid>de95fe37-d8f7-4447-82a1-79f4f1484dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/preceding::p[1]</value>
      <webElementGuid>98a57f5d-8556-4786-b186-d56e099b8479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Heaven'])[1]/preceding::p[1]</value>
      <webElementGuid>23a5942b-9863-4136-a39e-6e08fb95f8f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p[2]</value>
      <webElementGuid>7a33daf9-a03c-46d1-aca5-4dbc7e5cb46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'estTotal' and (text() = '฿350.00' or . = '฿350.00')]</value>
      <webElementGuid>cc109886-1a75-4d9e-b594-56cbaaba6513</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
