<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sub-total</name>
   <tag></tag>
   <elementGuidId>7d293f53-2d2d-480e-aba2-70dc7e0d927e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subtotal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='subtotal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e0829f28-4d8a-4508-b2b8-e13a2a86da61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-self-end</value>
      <webElementGuid>d0f98af6-4776-4f9d-941a-18df08bc5395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subtotal</value>
      <webElementGuid>2be4d3f1-4e0c-4395-90d1-babcfb72012e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>฿350.00</value>
      <webElementGuid>3d6a3795-b272-4ae0-b7cf-f109f157a997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subtotal&quot;)</value>
      <webElementGuid>79c0b5cf-4e67-409c-878f-b0e2c4f29b67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='subtotal']</value>
      <webElementGuid>d5312d37-6486-40aa-8fad-b1b9a70cdf06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::p[2]</value>
      <webElementGuid>2e9090d8-e349-407f-9fd3-43da391b00ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Promotion code'])[1]/following::p[2]</value>
      <webElementGuid>fab022a8-d8d8-4074-8532-b2558ef19a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/preceding::p[7]</value>
      <webElementGuid>825b2320-f148-4030-82b1-b477587f2b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Heaven'])[1]/preceding::p[7]</value>
      <webElementGuid>bbaaa8da-ef51-496b-ab51-b5d428273198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p[2]</value>
      <webElementGuid>c6ae193f-e862-4706-b18f-f661a6d68094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'subtotal' and (text() = '฿350.00' or . = '฿350.00')]</value>
      <webElementGuid>2cc5125d-0480-48bc-a862-1a276af24b67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
