<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Home_fas fa fa-th-large</name>
   <tag></tag>
   <elementGuidId>db7b1832-7f14-4d49-b732-4d4078c964e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[2]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa.fa-th-large</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d6f09ce8-08c0-4794-9c5c-50e9a40c2067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa fa-th-large</value>
      <webElementGuid>8ff6f00b-2703-4c2b-b93f-524dec2774ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d82c09d-c2e7-4162-a7d1-2a5143ccfc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;sidebar collapsed&quot;]/ul[@class=&quot;menu&quot;]/li[2]/a[1]/i[@class=&quot;fas fa fa-th-large&quot;]</value>
      <webElementGuid>2651fa19-ed42-421f-b443-101df6f8fcdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/i</value>
      <webElementGuid>66b24020-cd36-4e23-b429-0c7e62539833</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
